name: doc-test

on:
 push:
 pull_request:
 schedule:
  - cron: "0 0 * * *"

jobs:


  Matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:

      - name: Setup repository
        uses: actions/checkout@v2

      - name: Generate examples matrix
        id: generate
        run: ./.github/scripts/generate_job_matrix.py


  Test:
    needs: Matrix
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.Matrix.outputs.matrix) }}

    env:
      LANG: "en_US.UTF-8"
      DEBIAN_FRONTEND: "noninteractive"

    container: ${{matrix.os}}:${{matrix.os-version}}

    steps:
      - name: Setup repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install utils
        if: ${{matrix.os == 'ubuntu' || matrix.os == 'debian'}}
        run: apt -qqy update && apt -qqy install wget locales && locale-gen $LANG

      - name: Install utils
        if: ${{matrix.os == 'centos'}}
        run: yum -y install wget

      - name: Install tuttest
        run: |
          wget https://github.com/antmicro/tuttest/releases/download/v0.2-beta/tuttest -O /usr/bin/tuttest
          chmod a+rx /usr/bin/tuttest

      - name: Install SymbiFlow toolchain
        run: bash .github/scripts/install-toolchain.sh ${{matrix.fpga-fam}} ${{matrix.os}}

      - name: Build examples
        run: bash .github/scripts/build-examples.sh ${{matrix.fpga-fam}} ${{matrix.example}}

      - uses: actions/upload-artifact@v2
        with:
          name: symbiflow-examples-bitstreams
          path: |
            **/*.bit
            **/plot_*.svg
